### ISSUE TITLE
Breaks with django 1.6

### ISSUE THREAD

**Issue by diegox80** [django-oscar/django-oscar-accounts#26]
File "/home/diego/mydata/.virtualenvs/dropship/local/lib/python2.7/site-packages/accounts/dashboard/app.py", line 1, in <module>
from django.conf.urls.defaults import patterns, url
ImportError: No module named defaults

In django 1.6:
from django.conf.urls import patterns, url

**Comment by spac3-monkey** [comment]
You should look for the ``app.py`` in the path and change the:
```python
from django.conf.urls.defaults import patterns, url 
```
for this one
```python
from django.conf.urls import patterns, url

**Comment by solarissmoke** [comment]
Closing as Django 1.6 is no longer supported.
