### ISSUE TITLE
Running standalone on Django 1.7

### ISSUE THREAD

**Issue by jensenbox** [django-oscar/django-oscar-accounts#30]
There seems to be a System Check in Django 1.7 that is causing a fail when loading.

I am running oscar accounts as a standalone without oscar itself.

Here is the error:

accounts.Account.product_range: (fields.E300) Field defines a relation with model 'offer.Range', which is either not installed, or is abstract.

And here are the lines from abstract models that define the problem.

```
# Accounts are sometimes restricted to only work on a specific range of
# products.  This is the only link with Oscar.
product_range = models.ForeignKey('offer.Range', null=True, blank=True)
```

Do I need to install Oscar just to be able to use the accounts component?

**Comment by log0ymxm** [comment]
This seems to work. A fresh django 1.7 app also requires adding `treebeard` to your installed apps, and ensuring that `django.core.context_processors.request` is part of your context processors, as per the [treebeard config documentation](https://tabo.pe/projects/django-treebeard/docs/tip/install.html#configuration).

**Comment by solarissmoke** [comment]
Can no longer reproduce this issue, so closing.
