### ISSUE TITLE
Account swapping is not supported

### ISSUE THREAD

**Issue by theoriginalgri** [django-oscar/django-oscar-accounts#36]
https://github.com/tangentlabs/django-oscar-accounts/blob/master/accounts/abstract_models.py#L77 has "auth.User" as hardcoded value which makes it impossible to use a custom User implementation as described in http://django-oscar.readthedocs.org/en/releases-0.7/howto/use_a_custom_user_model.html

Edit: It seems this is already addressed by #34.

**Comment by solarissmoke** [comment]
Fixes in #34.
