### ISSUE TITLE
wrong logic for AllocationForm.get_max_amount

### ISSUE THREAD

**Issue by ijasperyang** [django-oscar/django-oscar-accounts#41]
problem occurs: order total= 20, you have 2 accounts with each balance is 10.

suggest:
return max_allocation - self.allocations.total
->
return min(max_allocation, self.order_total - self.allocations.total)

**Comment by solarissmoke** [comment]
I can't reproduce this - the logic for checking the order total seems to be correctly applied in `Account.permitted_allocation`. If it's still an issue please reopen with more detailed steps to reproduce.
