### ISSUE TITLE
Field defines a relation with model 'offer.Range', which is either not installed, or is abstract

### ISSUE THREAD

**Issue by kishan3** [django-oscar/django-oscar-accounts#42]
I am using Django==1.8.13, Ptyhon 3.5.1+

I installed  `django-oscar-accounts==0.4rc2.dev2+ngbe57d82` (latest master)

But I am getting following error when i do 
`python manage.py migrate oscar_accounts`

```
SystemCheckError: System check identified some issues:

ERRORS:
oscar_accounts.Account.product_range: (fields.E300) Field defines a relation with model 'offer.Range', which is either not installed, or is abstract.
`
```

**Comment by wtayyeb** [comment]
you have to create a dummy app named `offer` and a dummy model `Range` in `offer` to get it to work. or create a completly new Account model for yourself and use that instead.

**Comment by ratulotron** [comment]
Created and added an app called offer and then a dummy model Range in the app. Raises the following error:

    ValueError: Unhandled pending operations for models:
     offer.range (referred to by fields: oscar_accounts.Account.product_range)

**Comment by solarissmoke** [comment]
Not able to reproduce this - feel free to reopen if it's still an issue.
