### ISSUE TITLE
The description says (with or without oscar) but Oscar is a required dependency?

### ISSUE THREAD

**Issue by gabn88** [django-oscar/django-oscar-accounts#48]
So how can you use it without Oscar?

Edit: also there seems to be some open issues which have been fixed by #37, maybe it is a good idea to close them, because now the package looks unmaintained, while it is actually maintained.

**Comment by solarissmoke** [comment]
You can't... not since the code was changed to rely on Oscar's dynamic class loading. The migrations also expect some Oscar models and will fail without them.

I've removed this comment from the description. If someone is interested in making the app truly standalone then PR is welcome.
