### ISSUE TITLE
Can't run apps.checkout from sandbox

### ISSUE THREAD

**Issue by yn-coder** [django-oscar/django-oscar-accounts#55]
Can't run `apps.checkout` from [sandbox demo](https://github.com/django-oscar/django-oscar-accounts/blob/master/sandbox/apps/checkout/views.py)

With actual Django-Oscar and actual version of Django-Oscar-Accounts (from repo, not from pypi) - error message at `ctx['to_allocate'] = ctx['order_total_incl_tax'] - allocations.total` string.

What is `ctx['order_total_incl_tax']` ? May be `ctx['order_total'].incl_tax` ?

I think this is a bug in `apps.checkout`.

**Comment by solarissmoke** [comment]
Yeah, this is broken in several places. I tried a quick fix but ran into more issues further down (the way the `Allocations` are stored in the session is also broken). It's going to require a fair bit of refactoring to fix it I think.

**Comment by yn-coder** [comment]
@solarissmoke thank you!

It will be cool to have it fixed. Right now I work on internet store with prepayed service, and I have a plan to integrate the DO-Accounts in it.

Or can you publish some little example - how to integrate it?

**Comment by yn-coder** [comment]
I've done some example of DO and DOA integration, and it's look easy for basic transaction

```
    def handle_payment(self, order_number, total, **kwargs):
        # Take payment first
        user_accounts = gateway.user_accounts(self.request.user)

        destination_account = Account.objects.get(name="Sales")

        try:
            transfer = facade.transfer( user_accounts[0],
                                        destination_account,
                                        total.incl_tax,
                                        user=self.request.user,
                                        merchant_reference=order_number,
                                        description="Redeemed to pay for order %s" % order_number)
        except:
            facade.reverse( transfer, 
                            user=self.request.user,
                            merchant_reference=order_number,
                            description="Payment Cancellation" )
            raise PaymentError("Transfer Failed")
        else:
            # Payment successful! Record payment source
            source_type, __ = models.SourceType.objects.get_or_create(name="Accounts")
            source = models.Source( source_type=source_type,
                                    amount_allocated=total.incl_tax,
                                    reference=transfer.reference)
            self.add_payment_source(source)
            # Record payment event
            self.add_payment_event( "Transferred",
                                    transfer.amount,
                                    transfer.reference )
```

It's work (if we sure user really has an account), but very primitive.

Please, update your sandbox for proper example!
