### ISSUE TITLE
Not Oscar-independant

### ISSUE THREAD

**Issue by juaniisuar** [django-oscar/django-oscar-accounts#58]
Running

pip install django-oscar-accounts
(adding oscar_accounts to installed apps)
python manage.py migrate oscar_accounts

Yields:

SystemCheckError: System check identified some issues:

ERRORS:
oscar_accounts.Account.product_range: (fields.E300) Field defines a relation with model 'offer.Range', which is either not installed, or is abstract.
oscar_accounts.Account.product_range: (fields.E307) The field oscar_accounts.Account.product_range was declared with a lazy reference to 'offer.range', but app 'offer' isn't installed.

**Comment by solarissmoke** [comment]
Yeah, unfortunately it isn't. I've actually removed the suggestion that it is from the documentation on master - unless someone has the time to actually make it oscar-independent I think it will probably have to stay that way...

**Comment by juaniisuar** [comment]
Looking at the code for a bit i think it only references django-oscar for its user model and an exception class. It also references offer.Range with a ForeignKey which i think could be deleted. So yeah. making it oscar-independant might not be really hard after all.

**Comment by juaniisuar** [comment]
Right now i'm busy with two other projects, but i will try to do it i no one does.

**Comment by SalahAdDin** [comment]
what's the possible solution here? If you have time i can help you with this.

**Comment by millerf** [comment]
Hi, I would be really interested in using this as a standalone.
@juanigsrz I checked and removing the 'offer.Rang' foreign key doesn't seem so easy, or at least I am not sure on how to actually handle that...

**Comment by juanigsrz** [comment]
Hey @millerf , i personally ended up dropping it and made my own double entry system based on other working projects. Sorry i can't help you.

**Comment by millerf** [comment]
No worries... I just reused it and removed the `product_range` attribute...

**Comment by juanigsrz** [comment]
As @solarissmoke said, feel free to make a PR for review, i'm sure it'll be helpful to a lot of people!

**Comment by PekopT** [comment]
I'll just leave it here:
https://github.com/PekopT/django-oscar-accounts

**Comment by TurnrDev** [comment]
> I'll just leave it here:
> https://github.com/PekopT/django-oscar-accounts

Love the work, any plans to release the work on pypi?
