### ISSUE TITLE
Dependency mismatch: python-dateutil

### ISSUE THREAD

**Issue by PetrDlouhy** [django-oscar/django-oscar-accounts#60]
Current version (0.3) is not installable through pip due to `python-dateutil` version mismatch:
```
pip install django-oscar-accounts
....
faker 0.9.0 has requirement python-dateutil>=2.4, but you'll have python-dateutil 2.1 which is incompatible.
```

**Comment by solarissmoke** [comment]
This was fixed in https://github.com/django-oscar/django-oscar-accounts/commit/b4eabbaaae08a3fff922fd9ea69531b8caa2bca0 . I will see if I can put a new release on PyPi soon.
