### ISSUE TITLE
Missing 2.0.0 release tag

### ISSUE THREAD

**Issue by bartekgruszka** [django-oscar/django-oscar-accounts#77]
Release 2.0.0 is documented in the changelog https://github.com/django-oscar/django-oscar-accounts/blob/master/CHANGELOG.rst but git tag does not exists.

**Comment by bartekgruszka** [comment]
@solarissmoke

**Comment by solarissmoke** [comment]
Thanks - I've tagged it and published version 2.0.0 on pypi.
